export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'web-client',
        'web-api',
        'mcp-server',
        'telegram-bot',
        'core-shared',
        'core-client',
        'core-server',
        'scripts',
        'deps',
        'config',
        'changelog',
        'release',
        'spec',
      ],
    ],
    'scope-empty': [0, 'never'], // Allow commits without scope
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
  },
};
