packages:
  - '.'
  - packages/*

patchedDependencies:
  '@modelcontextprotocol/sdk@1.25.1': patches/@modelcontextprotocol__sdk@1.25.1.patch

auditConfig:
  ignoreCves:
    - CVE-2026-0621

overrides:
  jws: '>=4.0.0'
  qs: '>=6.14.1'
  systeminformation: '>=5.27.14'
  vite: '>=7.1.11'
  tar: '>=7.5.2'
  js-yaml: '>=4.1.1'
  tmp: '>=0.2.4'
  read-yaml-file: 2.1.0
  '@changesets/parse': '>=0.4.2'

allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  cpu-features: true
  dotenv-mono: true
  esbuild: true
  leveldown: true
  oxc-resolver: true
  protobufjs: true
  ssh2: true
  tldjs: true
  unrs-resolver: true
