/**
 * Environment file generation for setup wizard
 */

import chalk from 'chalk';
import fs from 'fs';
import path from 'path';

/**
 * Generate the minimal .env content for development
 */
function getEnvTemplate(): string {
  return `# Eddo Development Environment
# Generated by pnpm dev:setup on ${new Date().toISOString()}
# See .env.example for all available options

# CouchDB Configuration (matches docker-compose.yml defaults)
COUCHDB_URL=http://admin:password@localhost:5984
COUCHDB_DB_NAME=todos-dev

# Application Configuration
NODE_ENV=development
LOG_LEVEL=info

# MCP Server (for telegram bot and external integrations)
MCP_SERVER_URL=http://localhost:3001/mcp

# Disable browser telemetry (no OTEL collector running by default)
VITE_OTEL_ENABLED=false

# ============================================
# Optional: Uncomment and configure as needed
# ============================================

# Telegram Bot (get token from @BotFather)
# TELEGRAM_BOT_TOKEN=your_bot_token_from_botfather
# ANTHROPIC_API_KEY=your_anthropic_api_key

# Bot Persona: butler, gtd_coach, zen_master
# BOT_PERSONA_ID=butler

# LLM Model (default: claude-sonnet-4-0)
# LLM_MODEL=claude-sonnet-4-0
`;
}

/**
 * Generate minimal .env file for development
 */
export function generateEnvFile(rootDir: string, overwrite: boolean): boolean {
  const envPath = path.join(rootDir, '.env');

  if (fs.existsSync(envPath) && !overwrite) {
    console.log(chalk.yellow('  ⚠️  .env file already exists (use --force to overwrite)'));
    return false;
  }

  fs.writeFileSync(envPath, getEnvTemplate());
  console.log(chalk.green('  ✓ Generated .env file with development defaults'));
  return true;
}

/**
 * Check if .env file exists
 */
export function envFileExists(rootDir: string): boolean {
  return fs.existsSync(path.join(rootDir, '.env'));
}
