/**
 * Unit tests for env module
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { envFileExists, generateEnvFile } from './env.js';

// Spy on console.log to suppress output during tests
vi.spyOn(console, 'log').mockImplementation(() => {});

describe('env', () => {
  let testDir: string;

  beforeEach(() => {
    testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'env-test-'));
  });

  afterEach(() => {
    if (fs.existsSync(testDir)) {
      fs.rmSync(testDir, { recursive: true, force: true });
    }
  });

  describe('envFileExists', () => {
    it('returns true when .env exists', () => {
      fs.writeFileSync(path.join(testDir, '.env'), 'TEST=1');
      expect(envFileExists(testDir)).toBe(true);
    });

    it('returns false when .env does not exist', () => {
      expect(envFileExists(testDir)).toBe(false);
    });
  });

  describe('generateEnvFile', () => {
    it('creates .env file when it does not exist', () => {
      const result = generateEnvFile(testDir, false);

      expect(result).toBe(true);
      expect(fs.existsSync(path.join(testDir, '.env'))).toBe(true);
    });

    it('generates correct content structure', () => {
      generateEnvFile(testDir, false);

      const content = fs.readFileSync(path.join(testDir, '.env'), 'utf-8');

      // Check required configuration
      expect(content).toContain('COUCHDB_URL=http://admin:password@localhost:5984');
      expect(content).toContain('COUCHDB_DB_NAME=todos-dev');
      expect(content).toContain('NODE_ENV=development');
      expect(content).toContain('MCP_SERVER_URL=http://localhost:3001/mcp');
      expect(content).toContain('VITE_OTEL_ENABLED=false');
    });

    it('includes timestamp in generated file', () => {
      generateEnvFile(testDir, false);

      const content = fs.readFileSync(path.join(testDir, '.env'), 'utf-8');
      expect(content).toMatch(/Generated by pnpm setup on \d{4}-\d{2}-\d{2}/);
    });

    it('includes optional configuration section', () => {
      generateEnvFile(testDir, false);

      const content = fs.readFileSync(path.join(testDir, '.env'), 'utf-8');
      expect(content).toContain('TELEGRAM_BOT_TOKEN');
      expect(content).toContain('ANTHROPIC_API_KEY');
      expect(content).toContain('BOT_PERSONA_ID');
    });

    it('does not overwrite existing file when overwrite=false', () => {
      const existingContent = 'EXISTING=value';
      fs.writeFileSync(path.join(testDir, '.env'), existingContent);

      const result = generateEnvFile(testDir, false);

      expect(result).toBe(false);
      const content = fs.readFileSync(path.join(testDir, '.env'), 'utf-8');
      expect(content).toBe(existingContent);
    });

    it('overwrites existing file when overwrite=true', () => {
      fs.writeFileSync(path.join(testDir, '.env'), 'EXISTING=value');

      const result = generateEnvFile(testDir, true);

      expect(result).toBe(true);
      const content = fs.readFileSync(path.join(testDir, '.env'), 'utf-8');
      expect(content).toContain('COUCHDB_URL');
      expect(content).not.toContain('EXISTING=value');
    });
  });
});
