// Re-export everything from core-shared
export {
  DEFAULT_HEALTH_CONFIG,
  DatabaseErrorType,
  // Database monitoring
  DatabaseHealthMonitor,
  DatabaseOperationError,
  buildAttachmentDocId,
  createAuditLogEntry,
  createDefaultSessionStats,
  createDefaultUserPreferences,
  decodeJwtPayload,
  // Utils
  generateStableKey,
  getActiveDuration,
  getActiveRecordForActivities,
  getActiveRecordForTodos,
  getFormattedDuration,
  getFormattedDurationForActivities,
  getFormattedDurationForTodos,
  getRepeatTodo,
  getTokenExpiration,
  getTokenTimeRemaining,
  isAssistantMessage,
  isAuditLogAlpha1,
  isChatSession,
  isLatestUserRegistryVersion,
  isLatestVersion,
  isSessionMessageEntry,
  isTodoAlpha1,
  isTodoAlpha2,
  isTodoAlpha3,
  isTokenExpired,
  isToolResultMessage,
  isUserMessage,
  isUserRegistryEntryAlpha1,
  isUserRegistryEntryAlpha2,
  migrateToAlpha2,
  migrateToAlpha3,
  migrateTodo,
  migrateUserRegistryEntry,
  parseAttachmentDocId,
  shuffle,
  type Activity,
  // Chat types
  type AssistantMessage,
  // Attachment types
  type AttachmentDoc,
  // Audit log types
  type AuditAction,
  type AuditEntityType,
  type AuditLogAlpha1,
  type AuditSource,
  type BashExecutionMessage,
  type BranchSummaryEntry,
  type ChatMessage,
  type ChatMessageDoc,
  type ChatSession,
  type ChatSessionOperations,
  type CompactionEntry,
  type ContainerState,
  type ContentBlock,
  type CreateChatSessionRequest,
  type CreateUserRegistryEntry,
  type CreateUserRequest,
  type CustomEntry,
  type CustomMessage,
  type CustomMessageEntry,
  type DatabaseError,
  type DatabaseHealthCheck,
  type DatabaseHealthConfig,
  type DatabaseHealthIssue,
  type DatabaseHealthMetrics,
  type ImageContent,
  type LabelEntry,
  type LinkTelegramRequest,
  type LinkTelegramResponse,
  type LoginRequest,
  type LoginResponse,
  type MessageAttachment,
  type MessageRole,
  type ModelChangeEntry,
  type ModelProvider,
  type NewAuditLogEntry,
  // Types
  type NewTodo,
  type NewUserRegistryEntry,
  type RssFeedConfig,
  type SessionEntry,
  type SessionEntryBase,
  type SessionEntryType,
  type SessionHeaderEntry,
  type SessionInfoEntry,
  type SessionMessageEntry,
  type SessionRepository,
  type SessionStats,
  type StopReason,
  type TextContent,
  type ThinkingContent,
  type ThinkingLevel,
  type ThinkingLevelChangeEntry,
  type Todo,
  // API versions
  type TodoAlpha1,
  type TodoAlpha2,
  type TodoAlpha3,
  type TodoNote,
  type TokenUsage,
  type ToolCallContent,
  type ToolResultMessage,
  type UpdateChatSessionRequest,
  type UpdateUserRegistryEntry,
  type UserContext,
  type UserMessage,
  type UserPermission,
  type UserPermissions,
  type UserPreferences,
  type UserRegistryEntry,
  type UserRegistryEntryAlpha1,
  type UserRegistryEntryAlpha2,
  type UserRegistryOperations,
  type UserStatus,
  type WorktreeState,
} from '@eddo/core-shared';

// Server-specific configuration
export {
  createEnv,
  env,
  envSchema,
  getAvailableDatabases,
  getCouchDbConfig,
  getCouchDbUrl,
  getEffectiveDbName,
  getTestUserRegistryConfig,
  validateEnv,
  type Env,
} from './config';

// Server-specific API
export {
  AUDIT_SOURCES,
  createAuditDatabase,
  ensureAuditDatabase,
  getAuditDatabase,
  type AuditDatabase,
  type AuditEntriesBySource,
  type AuditListBySourceOptions,
  type AuditListOptions,
  type AuditListResult,
} from './api/audit-database';
export {
  clearAuditServiceCache,
  createAndInitializeAuditService,
  createAuditService,
  getAuditService,
  type AuditService,
  type LogActionOptions,
} from './api/audit-service';
export { createChatDatabase } from './api/chat-database';
export { setupChatDesignDocuments } from './api/chat-design-docs';
export { createDatabase, type DatabaseConfig, type DatabaseFactory } from './api/database-factory';
export { UserRegistry, createTestUserRegistry, createUserRegistry } from './api/user-registry';

// Server-specific utilities
export {
  extractUsernameFromDatabaseName,
  generateLinkingCode,
  getAllUserDatabaseNames,
  getAttachmentsDatabaseName,
  getAuditDatabaseConfig,
  getAuditDatabaseName,
  getChatDatabaseConfig,
  getChatDatabaseName,
  getDatabasePrefix,
  getUserDatabaseConfig,
  getUserDatabaseName,
  getUserRegistryDatabaseConfig,
  getUserRegistryDatabaseName,
  isAuditDatabase,
  isChatDatabase,
  isUserDatabase,
  isUserRegistryDatabase,
  sanitizeUsername,
} from './utils/database-names';
export {
  cleanupCIEnvironment,
  cleanupDatabasesByPattern,
  cleanupUserDatabases,
  createTestCleanup,
  getDatabaseReport,
  quickCleanup,
  type CleanupResult,
  type DatabaseInfo,
  type TestCleanupOptions,
  type TestDatabaseCleanup,
} from './utils/test-cleanup';
