// Re-export everything from core-shared
export {
  DEFAULT_HEALTH_CONFIG,
  DatabaseErrorType,
  // Database monitoring
  DatabaseHealthMonitor,
  DatabaseOperationError,
  createAuditLogEntry,
  createDefaultUserPreferences,
  decodeJwtPayload,
  // Utils
  generateStableKey,
  getActiveDuration,
  getActiveRecordForActivities,
  getActiveRecordForTodos,
  getFormattedDuration,
  getFormattedDurationForActivities,
  getFormattedDurationForTodos,
  getRepeatTodo,
  getTokenExpiration,
  getTokenTimeRemaining,
  isAuditLogAlpha1,
  isLatestUserRegistryVersion,
  isLatestVersion,
  isTodoAlpha1,
  isTodoAlpha2,
  isTodoAlpha3,
  isTokenExpired,
  isUserRegistryEntryAlpha1,
  isUserRegistryEntryAlpha2,
  migrateToAlpha2,
  migrateToAlpha3,
  migrateTodo,
  migrateUserRegistryEntry,
  shuffle,
  type Activity,
  // Audit log types
  type AuditAction,
  type AuditEntityType,
  type AuditLogAlpha1,
  type AuditSource,
  type CreateUserRegistryEntry,
  type CreateUserRequest,
  type DatabaseError,
  type DatabaseHealthCheck,
  type DatabaseHealthConfig,
  type DatabaseHealthIssue,
  type DatabaseHealthMetrics,
  type LinkTelegramRequest,
  type LinkTelegramResponse,
  type LoginRequest,
  type LoginResponse,
  type NewAuditLogEntry,
  // Types
  type NewTodo,
  type NewUserRegistryEntry,
  type RssFeedConfig,
  type Todo,
  // API versions
  type TodoAlpha1,
  type TodoAlpha2,
  type TodoAlpha3,
  type TodoNote,
  type UpdateUserRegistryEntry,
  type UserContext,
  type UserPermission,
  type UserPermissions,
  type UserPreferences,
  type UserRegistryEntry,
  type UserRegistryEntryAlpha1,
  type UserRegistryEntryAlpha2,
  type UserRegistryOperations,
  type UserStatus,
} from '@eddo/core-shared';

// Server-specific configuration
export {
  createEnv,
  env,
  envSchema,
  getAvailableDatabases,
  getCouchDbConfig,
  getCouchDbUrl,
  getEffectiveDbName,
  getTestUserRegistryConfig,
  validateEnv,
  type Env,
} from './config';

// Server-specific API
export {
  createAuditDatabase,
  ensureAuditDatabase,
  getAuditDatabase,
  type AuditDatabase,
  type AuditListOptions,
  type AuditListResult,
} from './api/audit-database';
export {
  clearAuditServiceCache,
  createAndInitializeAuditService,
  createAuditService,
  getAuditService,
  type AuditService,
  type LogActionOptions,
} from './api/audit-service';
export { createDatabase, type DatabaseConfig, type DatabaseFactory } from './api/database-factory';
export { UserRegistry, createTestUserRegistry, createUserRegistry } from './api/user-registry';

// Server-specific utilities
export {
  extractUsernameFromDatabaseName,
  generateLinkingCode,
  getAllUserDatabaseNames,
  getAuditDatabaseConfig,
  getAuditDatabaseName,
  getDatabasePrefix,
  getUserDatabaseConfig,
  getUserDatabaseName,
  getUserRegistryDatabaseConfig,
  getUserRegistryDatabaseName,
  isAuditDatabase,
  isUserDatabase,
  isUserRegistryDatabase,
  sanitizeUsername,
} from './utils/database-names';
export {
  cleanupCIEnvironment,
  cleanupDatabasesByPattern,
  cleanupUserDatabases,
  createTestCleanup,
  getDatabaseReport,
  quickCleanup,
  type CleanupResult,
  type DatabaseInfo,
  type TestCleanupOptions,
  type TestDatabaseCleanup,
} from './utils/test-cleanup';
